service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          # Agregramos el codigo arn al rol, el cual lo podemos encontrar en Dynamodb -> usersTable -> Información general -> Información adicional -> ARN
          Resource: arn:aws:dynamodb:us-east-1:471112938813:table/${self:provider.environment.USERS_TABLE}
  environment:
    # Establecemos nuestras variables de entorno para ser usadas como "self:provider..environment" o "process.env"
    USERS_TABLE: usersTable

functions:
  createUser:
    handler: ./createUsers/handler.createUser
    events:
      - http:
          path: users
          method: post

  getUser:
    handler: ./getUsers/handler.getUsers
    events:
      - http:
          path: users/{id}
          method: get

  updateUser:
    handler: ./updateUser/handler.updateUser
    events:
      - http:
          path: users/{id}
          method: put

  deleteUser:
    handler: ./deleteUser/handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
